version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
    command: yarn dev
